// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CLIScriptSupporter is an autogenerated mock type for the CLIScriptSupporter type
type CLIScriptSupporter struct {
	mock.Mock
}

type CLIScriptSupporter_Expecter struct {
	mock *mock.Mock
}

func (_m *CLIScriptSupporter) EXPECT() *CLIScriptSupporter_Expecter {
	return &CLIScriptSupporter_Expecter{mock: &_m.Mock}
}

// ListOfEntries provides a mock function with given fields: ctx, entries
func (_m *CLIScriptSupporter) ListOfEntries(ctx context.Context, entries []string) (int, error) {
	ret := _m.Called(ctx, entries)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, []string) int); ok {
		r0 = rf(ctx, entries)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, entries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CLIScriptSupporter_ListOfEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOfEntries'
type CLIScriptSupporter_ListOfEntries_Call struct {
	*mock.Call
}

// ListOfEntries is a helper method to define mock.On call
//  - ctx context.Context
//  - entries []string
func (_e *CLIScriptSupporter_Expecter) ListOfEntries(ctx interface{}, entries interface{}) *CLIScriptSupporter_ListOfEntries_Call {
	return &CLIScriptSupporter_ListOfEntries_Call{Call: _e.mock.On("ListOfEntries", ctx, entries)}
}

func (_c *CLIScriptSupporter_ListOfEntries_Call) Run(run func(ctx context.Context, entries []string)) *CLIScriptSupporter_ListOfEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CLIScriptSupporter_ListOfEntries_Call) Return(_a0 int, _a1 error) *CLIScriptSupporter_ListOfEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Login provides a mock function with given fields: ctx
func (_m *CLIScriptSupporter) Login(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CLIScriptSupporter_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type CLIScriptSupporter_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//  - ctx context.Context
func (_e *CLIScriptSupporter_Expecter) Login(ctx interface{}) *CLIScriptSupporter_Login_Call {
	return &CLIScriptSupporter_Login_Call{Call: _e.mock.On("Login", ctx)}
}

func (_c *CLIScriptSupporter_Login_Call) Run(run func(ctx context.Context)) *CLIScriptSupporter_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CLIScriptSupporter_Login_Call) Return(_a0 interface{}, _a1 error) *CLIScriptSupporter_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Registration provides a mock function with given fields: ctx
func (_m *CLIScriptSupporter) Registration(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CLIScriptSupporter_Registration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Registration'
type CLIScriptSupporter_Registration_Call struct {
	*mock.Call
}

// Registration is a helper method to define mock.On call
//  - ctx context.Context
func (_e *CLIScriptSupporter_Expecter) Registration(ctx interface{}) *CLIScriptSupporter_Registration_Call {
	return &CLIScriptSupporter_Registration_Call{Call: _e.mock.On("Registration", ctx)}
}

func (_c *CLIScriptSupporter_Registration_Call) Run(run func(ctx context.Context)) *CLIScriptSupporter_Registration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CLIScriptSupporter_Registration_Call) Return(_a0 interface{}, _a1 error) *CLIScriptSupporter_Registration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SelectCommand provides a mock function with given fields: ctx, options
func (_m *CLIScriptSupporter) SelectCommand(ctx context.Context, options []string) (string, error) {
	ret := _m.Called(ctx, options)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, []string) string); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CLIScriptSupporter_SelectCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectCommand'
type CLIScriptSupporter_SelectCommand_Call struct {
	*mock.Call
}

// SelectCommand is a helper method to define mock.On call
//  - ctx context.Context
//  - options []string
func (_e *CLIScriptSupporter_Expecter) SelectCommand(ctx interface{}, options interface{}) *CLIScriptSupporter_SelectCommand_Call {
	return &CLIScriptSupporter_SelectCommand_Call{Call: _e.mock.On("SelectCommand", ctx, options)}
}

func (_c *CLIScriptSupporter_SelectCommand_Call) Run(run func(ctx context.Context, options []string)) *CLIScriptSupporter_SelectCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CLIScriptSupporter_SelectCommand_Call) Return(_a0 string, _a1 error) *CLIScriptSupporter_SelectCommand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SelectLoginMethod provides a mock function with given fields: ctx, options
func (_m *CLIScriptSupporter) SelectLoginMethod(ctx context.Context, options []string) (string, error) {
	ret := _m.Called(ctx, options)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, []string) string); ok {
		r0 = rf(ctx, options)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CLIScriptSupporter_SelectLoginMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectLoginMethod'
type CLIScriptSupporter_SelectLoginMethod_Call struct {
	*mock.Call
}

// SelectLoginMethod is a helper method to define mock.On call
//  - ctx context.Context
//  - options []string
func (_e *CLIScriptSupporter_Expecter) SelectLoginMethod(ctx interface{}, options interface{}) *CLIScriptSupporter_SelectLoginMethod_Call {
	return &CLIScriptSupporter_SelectLoginMethod_Call{Call: _e.mock.On("SelectLoginMethod", ctx, options)}
}

func (_c *CLIScriptSupporter_SelectLoginMethod_Call) Run(run func(ctx context.Context, options []string)) *CLIScriptSupporter_SelectLoginMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CLIScriptSupporter_SelectLoginMethod_Call) Return(_a0 string, _a1 error) *CLIScriptSupporter_SelectLoginMethod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SetEntry provides a mock function with given fields: ctx, types
func (_m *CLIScriptSupporter) SetEntry(ctx context.Context, types []string) (interface{}, error) {
	ret := _m.Called(ctx, types)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, []string) interface{}); ok {
		r0 = rf(ctx, types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, types)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CLIScriptSupporter_SetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEntry'
type CLIScriptSupporter_SetEntry_Call struct {
	*mock.Call
}

// SetEntry is a helper method to define mock.On call
//  - ctx context.Context
//  - types []string
func (_e *CLIScriptSupporter_Expecter) SetEntry(ctx interface{}, types interface{}) *CLIScriptSupporter_SetEntry_Call {
	return &CLIScriptSupporter_SetEntry_Call{Call: _e.mock.On("SetEntry", ctx, types)}
}

func (_c *CLIScriptSupporter_SetEntry_Call) Run(run func(ctx context.Context, types []string)) *CLIScriptSupporter_SetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CLIScriptSupporter_SetEntry_Call) Return(_a0 interface{}, _a1 error) *CLIScriptSupporter_SetEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewCLIScriptSupporter interface {
	mock.TestingT
	Cleanup(func())
}

// NewCLIScriptSupporter creates a new instance of CLIScriptSupporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCLIScriptSupporter(t mockConstructorTestingTNewCLIScriptSupporter) *CLIScriptSupporter {
	mock := &CLIScriptSupporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
