// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// GRPCClientSetSupporter is an autogenerated mock type for the GRPCClientSetSupporter type
type GRPCClientSetSupporter struct {
	mock.Mock
}

type GRPCClientSetSupporter_Expecter struct {
	mock *mock.Mock
}

func (_m *GRPCClientSetSupporter) EXPECT() *GRPCClientSetSupporter_Expecter {
	return &GRPCClientSetSupporter_Expecter{mock: &_m.Mock}
}

// SetEntry provides a mock function with given fields: ctx, typeID, name, metadata, data
func (_m *GRPCClientSetSupporter) SetEntry(ctx context.Context, typeID string, name string, metadata string, data []byte) error {
	ret := _m.Called(ctx, typeID, name, metadata, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) error); ok {
		r0 = rf(ctx, typeID, name, metadata, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GRPCClientSetSupporter_SetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEntry'
type GRPCClientSetSupporter_SetEntry_Call struct {
	*mock.Call
}

// SetEntry is a helper method to define mock.On call
//  - ctx context.Context
//  - typeID string
//  - name string
//  - metadata string
//  - data []byte
func (_e *GRPCClientSetSupporter_Expecter) SetEntry(ctx interface{}, typeID interface{}, name interface{}, metadata interface{}, data interface{}) *GRPCClientSetSupporter_SetEntry_Call {
	return &GRPCClientSetSupporter_SetEntry_Call{Call: _e.mock.On("SetEntry", ctx, typeID, name, metadata, data)}
}

func (_c *GRPCClientSetSupporter_SetEntry_Call) Run(run func(ctx context.Context, typeID string, name string, metadata string, data []byte)) *GRPCClientSetSupporter_SetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]byte))
	})
	return _c
}

func (_c *GRPCClientSetSupporter_SetEntry_Call) Return(_a0 error) *GRPCClientSetSupporter_SetEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewGRPCClientSetSupporter interface {
	mock.TestingT
	Cleanup(func())
}

// NewGRPCClientSetSupporter creates a new instance of GRPCClientSetSupporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGRPCClientSetSupporter(t mockConstructorTestingTNewGRPCClientSetSupporter) *GRPCClientSetSupporter {
	mock := &GRPCClientSetSupporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
