// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Decryptor is an autogenerated mock type for the Decryptor type
type Decryptor struct {
	mock.Mock
}

type Decryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *Decryptor) EXPECT() *Decryptor_Expecter {
	return &Decryptor_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: encrypted
func (_m *Decryptor) Decrypt(encrypted string) ([]byte, error) {
	ret := _m.Called(encrypted)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(encrypted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encrypted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Decryptor_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type Decryptor_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//  - encrypted string
func (_e *Decryptor_Expecter) Decrypt(encrypted interface{}) *Decryptor_Decrypt_Call {
	return &Decryptor_Decrypt_Call{Call: _e.mock.On("Decrypt", encrypted)}
}

func (_c *Decryptor_Decrypt_Call) Run(run func(encrypted string)) *Decryptor_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Decryptor_Decrypt_Call) Return(_a0 []byte, _a1 error) *Decryptor_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewDecryptor interface {
	mock.TestingT
	Cleanup(func())
}

// NewDecryptor creates a new instance of Decryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDecryptor(t mockConstructorTestingTNewDecryptor) *Decryptor {
	mock := &Decryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
