// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// EntryChanger is an autogenerated mock type for the EntryChanger type
type EntryChanger struct {
	mock.Mock
}

type EntryChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *EntryChanger) EXPECT() *EntryChanger_Expecter {
	return &EntryChanger_Expecter{mock: &_m.Mock}
}

// Change provides a mock function with given fields: ctx, entry
func (_m *EntryChanger) Change(ctx context.Context, entry *entity.Entry) error {
	ret := _m.Called(ctx, entry)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Entry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EntryChanger_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type EntryChanger_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//  - ctx context.Context
//  - entry *entity.Entry
func (_e *EntryChanger_Expecter) Change(ctx interface{}, entry interface{}) *EntryChanger_Change_Call {
	return &EntryChanger_Change_Call{Call: _e.mock.On("Change", ctx, entry)}
}

func (_c *EntryChanger_Change_Call) Run(run func(ctx context.Context, entry *entity.Entry)) *EntryChanger_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Entry))
	})
	return _c
}

func (_c *EntryChanger_Change_Call) Return(_a0 error) *EntryChanger_Change_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewEntryChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntryChanger creates a new instance of EntryChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntryChanger(t mockConstructorTestingTNewEntryChanger) *EntryChanger {
	mock := &EntryChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
