// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// EntryAllByUserGetter is an autogenerated mock type for the EntryAllByUserGetter type
type EntryAllByUserGetter struct {
	mock.Mock
}

type EntryAllByUserGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *EntryAllByUserGetter) EXPECT() *EntryAllByUserGetter_Expecter {
	return &EntryAllByUserGetter_Expecter{mock: &_m.Mock}
}

// GetAllByUser provides a mock function with given fields: ctx, user
func (_m *EntryAllByUserGetter) GetAllByUser(ctx context.Context, user *entity.User) ([]*entity.Entry, error) {
	ret := _m.Called(ctx, user)

	var r0 []*entity.Entry
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) []*entity.Entry); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Entry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EntryAllByUserGetter_GetAllByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByUser'
type EntryAllByUserGetter_GetAllByUser_Call struct {
	*mock.Call
}

// GetAllByUser is a helper method to define mock.On call
//  - ctx context.Context
//  - user *entity.User
func (_e *EntryAllByUserGetter_Expecter) GetAllByUser(ctx interface{}, user interface{}) *EntryAllByUserGetter_GetAllByUser_Call {
	return &EntryAllByUserGetter_GetAllByUser_Call{Call: _e.mock.On("GetAllByUser", ctx, user)}
}

func (_c *EntryAllByUserGetter_GetAllByUser_Call) Run(run func(ctx context.Context, user *entity.User)) *EntryAllByUserGetter_GetAllByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *EntryAllByUserGetter_GetAllByUser_Call) Return(_a0 []*entity.Entry, _a1 error) *EntryAllByUserGetter_GetAllByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewEntryAllByUserGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntryAllByUserGetter creates a new instance of EntryAllByUserGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntryAllByUserGetter(t mockConstructorTestingTNewEntryAllByUserGetter) *EntryAllByUserGetter {
	mock := &EntryAllByUserGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
