// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// EntryGetter is an autogenerated mock type for the EntryGetter type
type EntryGetter struct {
	mock.Mock
}

type EntryGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *EntryGetter) EXPECT() *EntryGetter_Expecter {
	return &EntryGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, entryID
func (_m *EntryGetter) Get(ctx context.Context, entryID uuid.UUID) (*entity.Entry, error) {
	ret := _m.Called(ctx, entryID)

	var r0 *entity.Entry
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Entry); ok {
		r0 = rf(ctx, entryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Entry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, entryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EntryGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type EntryGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - ctx context.Context
//  - entryID uuid.UUID
func (_e *EntryGetter_Expecter) Get(ctx interface{}, entryID interface{}) *EntryGetter_Get_Call {
	return &EntryGetter_Get_Call{Call: _e.mock.On("Get", ctx, entryID)}
}

func (_c *EntryGetter_Get_Call) Run(run func(ctx context.Context, entryID uuid.UUID)) *EntryGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *EntryGetter_Get_Call) Return(_a0 *entity.Entry, _a1 error) *EntryGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewEntryGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewEntryGetter creates a new instance of EntryGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEntryGetter(t mockConstructorTestingTNewEntryGetter) *EntryGetter {
	mock := &EntryGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
