// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

type Server_Expecter struct {
	mock *mock.Mock
}

func (_m *Server) EXPECT() *Server_Expecter {
	return &Server_Expecter{mock: &_m.Mock}
}

// Serve provides a mock function with given fields: handlerCollection
func (_m *Server) Serve(handlerCollection interface{}) error {
	ret := _m.Called(handlerCollection)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(handlerCollection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Server_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type Server_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//  - handlerCollection interface{}
func (_e *Server_Expecter) Serve(handlerCollection interface{}) *Server_Serve_Call {
	return &Server_Serve_Call{Call: _e.mock.On("Serve", handlerCollection)}
}

func (_c *Server_Serve_Call) Run(run func(handlerCollection interface{})) *Server_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Server_Serve_Call) Return(_a0 error) *Server_Serve_Call {
	_c.Call.Return(_a0)
	return _c
}

// Shutdown provides a mock function with given fields:
func (_m *Server) Shutdown() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Server_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Server_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *Server_Expecter) Shutdown() *Server_Shutdown_Call {
	return &Server_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *Server_Shutdown_Call) Run(run func()) *Server_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Server_Shutdown_Call) Return(_a0 error) *Server_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServer(t mockConstructorTestingTNewServer) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
