// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SessionGetter is an autogenerated mock type for the SessionGetter type
type SessionGetter struct {
	mock.Mock
}

type SessionGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionGetter) EXPECT() *SessionGetter_Expecter {
	return &SessionGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, sessionID
func (_m *SessionGetter) Get(ctx context.Context, sessionID uuid.UUID) (*entity.Session, error) {
	ret := _m.Called(ctx, sessionID)

	var r0 *entity.Session
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - ctx context.Context
//  - sessionID uuid.UUID
func (_e *SessionGetter_Expecter) Get(ctx interface{}, sessionID interface{}) *SessionGetter_Get_Call {
	return &SessionGetter_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *SessionGetter_Get_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionGetter_Get_Call) Return(_a0 *entity.Session, _a1 error) *SessionGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewSessionGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionGetter creates a new instance of SessionGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionGetter(t mockConstructorTestingTNewSessionGetter) *SessionGetter {
	mock := &SessionGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
