// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// SessionChanger is an autogenerated mock type for the SessionChanger type
type SessionChanger struct {
	mock.Mock
}

type SessionChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionChanger) EXPECT() *SessionChanger_Expecter {
	return &SessionChanger_Expecter{mock: &_m.Mock}
}

// Change provides a mock function with given fields: ctx, session
func (_m *SessionChanger) Change(ctx context.Context, session *entity.Session) error {
	ret := _m.Called(ctx, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionChanger_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type SessionChanger_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//  - ctx context.Context
//  - session *entity.Session
func (_e *SessionChanger_Expecter) Change(ctx interface{}, session interface{}) *SessionChanger_Change_Call {
	return &SessionChanger_Change_Call{Call: _e.mock.On("Change", ctx, session)}
}

func (_c *SessionChanger_Change_Call) Run(run func(ctx context.Context, session *entity.Session)) *SessionChanger_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Session))
	})
	return _c
}

func (_c *SessionChanger_Change_Call) Return(_a0 error) *SessionChanger_Change_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewSessionChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionChanger creates a new instance of SessionChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionChanger(t mockConstructorTestingTNewSessionChanger) *SessionChanger {
	mock := &SessionChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
