// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, session
func (_m *SessionRepository) Add(ctx context.Context, session *entity.Session) error {
	ret := _m.Called(ctx, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type SessionRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//  - ctx context.Context
//  - session *entity.Session
func (_e *SessionRepository_Expecter) Add(ctx interface{}, session interface{}) *SessionRepository_Add_Call {
	return &SessionRepository_Add_Call{Call: _e.mock.On("Add", ctx, session)}
}

func (_c *SessionRepository_Add_Call) Run(run func(ctx context.Context, session *entity.Session)) *SessionRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Session))
	})
	return _c
}

func (_c *SessionRepository_Add_Call) Return(_a0 error) *SessionRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

// Change provides a mock function with given fields: ctx, session
func (_m *SessionRepository) Change(ctx context.Context, session *entity.Session) error {
	ret := _m.Called(ctx, session)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type SessionRepository_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//  - ctx context.Context
//  - session *entity.Session
func (_e *SessionRepository_Expecter) Change(ctx interface{}, session interface{}) *SessionRepository_Change_Call {
	return &SessionRepository_Change_Call{Call: _e.mock.On("Change", ctx, session)}
}

func (_c *SessionRepository_Change_Call) Run(run func(ctx context.Context, session *entity.Session)) *SessionRepository_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Session))
	})
	return _c
}

func (_c *SessionRepository_Change_Call) Return(_a0 error) *SessionRepository_Change_Call {
	_c.Call.Return(_a0)
	return _c
}

// Get provides a mock function with given fields: ctx, sessionID
func (_m *SessionRepository) Get(ctx context.Context, sessionID uuid.UUID) (*entity.Session, error) {
	ret := _m.Called(ctx, sessionID)

	var r0 *entity.Session
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - ctx context.Context
//  - sessionID uuid.UUID
func (_e *SessionRepository_Expecter) Get(ctx interface{}, sessionID interface{}) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *SessionRepository_Get_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(_a0 *entity.Session, _a1 error) *SessionRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Remove provides a mock function with given fields: ctx, sessionID
func (_m *SessionRepository) Remove(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type SessionRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//  - ctx context.Context
//  - sessionID uuid.UUID
func (_e *SessionRepository_Expecter) Remove(ctx interface{}, sessionID interface{}) *SessionRepository_Remove_Call {
	return &SessionRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, sessionID)}
}

func (_c *SessionRepository_Remove_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *SessionRepository_Remove_Call) Return(_a0 error) *SessionRepository_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewSessionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionRepository(t mockConstructorTestingTNewSessionRepository) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
