// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// TypeChanger is an autogenerated mock type for the TypeChanger type
type TypeChanger struct {
	mock.Mock
}

type TypeChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *TypeChanger) EXPECT() *TypeChanger_Expecter {
	return &TypeChanger_Expecter{mock: &_m.Mock}
}

// Change provides a mock function with given fields: ctx, tp
func (_m *TypeChanger) Change(ctx context.Context, tp *entity.Type) error {
	ret := _m.Called(ctx, tp)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Type) error); ok {
		r0 = rf(ctx, tp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TypeChanger_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type TypeChanger_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//  - ctx context.Context
//  - tp *entity.Type
func (_e *TypeChanger_Expecter) Change(ctx interface{}, tp interface{}) *TypeChanger_Change_Call {
	return &TypeChanger_Change_Call{Call: _e.mock.On("Change", ctx, tp)}
}

func (_c *TypeChanger_Change_Call) Run(run func(ctx context.Context, tp *entity.Type)) *TypeChanger_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Type))
	})
	return _c
}

func (_c *TypeChanger_Change_Call) Return(_a0 error) *TypeChanger_Change_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewTypeChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewTypeChanger creates a new instance of TypeChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTypeChanger(t mockConstructorTestingTNewTypeChanger) *TypeChanger {
	mock := &TypeChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
