// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserGetter is an autogenerated mock type for the UserGetter type
type UserGetter struct {
	mock.Mock
}

type UserGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserGetter) EXPECT() *UserGetter_Expecter {
	return &UserGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *UserGetter) Get(ctx context.Context, userID uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//  - ctx context.Context
//  - userID uuid.UUID
func (_e *UserGetter_Expecter) Get(ctx interface{}, userID interface{}) *UserGetter_Get_Call {
	return &UserGetter_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *UserGetter_Get_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserGetter_Get_Call) Return(_a0 *entity.User, _a1 error) *UserGetter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewUserGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserGetter creates a new instance of UserGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserGetter(t mockConstructorTestingTNewUserGetter) *UserGetter {
	mock := &UserGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
