// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// UserRemover is an autogenerated mock type for the UserRemover type
type UserRemover struct {
	mock.Mock
}

type UserRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRemover) EXPECT() *UserRemover_Expecter {
	return &UserRemover_Expecter{mock: &_m.Mock}
}

// Remove provides a mock function with given fields: ctx, userID
func (_m *UserRemover) Remove(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRemover_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type UserRemover_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//  - ctx context.Context
//  - userID uuid.UUID
func (_e *UserRemover_Expecter) Remove(ctx interface{}, userID interface{}) *UserRemover_Remove_Call {
	return &UserRemover_Remove_Call{Call: _e.mock.On("Remove", ctx, userID)}
}

func (_c *UserRemover_Remove_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserRemover_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *UserRemover_Remove_Call) Return(_a0 error) *UserRemover_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUserRemover interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRemover creates a new instance of UserRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRemover(t mockConstructorTestingTNewUserRemover) *UserRemover {
	mock := &UserRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
