// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserAdder is an autogenerated mock type for the UserAdder type
type UserAdder struct {
	mock.Mock
}

type UserAdder_Expecter struct {
	mock *mock.Mock
}

func (_m *UserAdder) EXPECT() *UserAdder_Expecter {
	return &UserAdder_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, user
func (_m *UserAdder) Add(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserAdder_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type UserAdder_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//  - ctx context.Context
//  - user *entity.User
func (_e *UserAdder_Expecter) Add(ctx interface{}, user interface{}) *UserAdder_Add_Call {
	return &UserAdder_Add_Call{Call: _e.mock.On("Add", ctx, user)}
}

func (_c *UserAdder_Add_Call) Run(run func(ctx context.Context, user *entity.User)) *UserAdder_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *UserAdder_Add_Call) Return(_a0 error) *UserAdder_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUserAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserAdder creates a new instance of UserAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserAdder(t mockConstructorTestingTNewUserAdder) *UserAdder {
	mock := &UserAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
