// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserChanger is an autogenerated mock type for the UserChanger type
type UserChanger struct {
	mock.Mock
}

type UserChanger_Expecter struct {
	mock *mock.Mock
}

func (_m *UserChanger) EXPECT() *UserChanger_Expecter {
	return &UserChanger_Expecter{mock: &_m.Mock}
}

// Change provides a mock function with given fields: ctx, user
func (_m *UserChanger) Change(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserChanger_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type UserChanger_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//  - ctx context.Context
//  - user *entity.User
func (_e *UserChanger_Expecter) Change(ctx interface{}, user interface{}) *UserChanger_Change_Call {
	return &UserChanger_Change_Call{Call: _e.mock.On("Change", ctx, user)}
}

func (_c *UserChanger_Change_Call) Run(run func(ctx context.Context, user *entity.User)) *UserChanger_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *UserChanger_Change_Call) Return(_a0 error) *UserChanger_Change_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUserChanger interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserChanger creates a new instance of UserChanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserChanger(t mockConstructorTestingTNewUserChanger) *UserChanger {
	mock := &UserChanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
