// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/alrund/yp-2-project/server/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserByLoginGetter is an autogenerated mock type for the UserByLoginGetter type
type UserByLoginGetter struct {
	mock.Mock
}

type UserByLoginGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *UserByLoginGetter) EXPECT() *UserByLoginGetter_Expecter {
	return &UserByLoginGetter_Expecter{mock: &_m.Mock}
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *UserByLoginGetter) GetByLogin(ctx context.Context, login string) (*entity.User, error) {
	ret := _m.Called(ctx, login)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserByLoginGetter_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type UserByLoginGetter_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//  - ctx context.Context
//  - login string
func (_e *UserByLoginGetter_Expecter) GetByLogin(ctx interface{}, login interface{}) *UserByLoginGetter_GetByLogin_Call {
	return &UserByLoginGetter_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *UserByLoginGetter_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *UserByLoginGetter_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserByLoginGetter_GetByLogin_Call) Return(_a0 *entity.User, _a1 error) *UserByLoginGetter_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewUserByLoginGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserByLoginGetter creates a new instance of UserByLoginGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserByLoginGetter(t mockConstructorTestingTNewUserByLoginGetter) *UserByLoginGetter {
	mock := &UserByLoginGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
